### ISSUE TITLE
Reorganizing repo

### ISSUE THREAD

**Issue by cwbeltz** [NCEAS/metadig-dataone-fair#3]
I will try and re-organize the repo in one of my next PRs, to integrate my code a bit more fully.

**Comment by gothub** [comment]
@cwbeltz how are you proposing to re-organize the repo? If you want to change the directory structure or add new directories, could you provide your proposed layout in this issue before creating the PR?

**Comment by cwbeltz** [comment]
@gothub I'll make sure to propose it here before re-organizing.

**Comment by cwbeltz** [comment]
So proposed structure is similar to whats already here, but includes a couple additional directories. I'll also re-home some of the scripts to the 'code' folder, reports to 'reports', etc.

***Additional question: _Should I include the data?_ I do see some CSVs in here, but wanted to confirm before adding them. The data includes individual checks, aggregate FAIR scores, and Google analytics views.

```
|_ code
    |_ Aggregate-Scores
    |_ Google-Analytics_views
    |_ Individual-Checks
|_ data***
    |_ Aggregate-Scores
      |_ raw
    |_ Google-Analytics_views
      |_ raw
    |_ Individual-Checks
      |_ raw
|_ figures
|_ reports
```

**Comment by cwbeltz** [comment]
@gothub slight addition to the proposed directory structure above to include /docs in the root directory of the repo for github pages
